INSERT INTO Author (AuthorID, AuthorName)
VALUES 
    ('A001', 'Michael J. Hernandez'),
    ('A002', 'Thomas H. Cormen'),
    ('A003', 'Elisabeth Freeman'),
    ('A004', 'Robert C. Martin'),
    ('A005', 'Margaret Wise Brown'),
    ('A006', 'William E. Shotts, Jr.'),
    ('A007', 'Foster Provost'),
    ('A008', 'Martin Kleppmann'),
    ('A009', 'Al Sweigart'),
    ('A010', 'Stuart Russell'),
    ('A011', 'Ian Goodfellow'),
    ('A012', 'Aurélien Géron'),
    ('A013', 'Richard S. Sutton'),
    ('A014', 'Frederick P. Brooks Jr.'),
    ('A015', 'Erich Gamma'),
    ('A016', 'Eric Matthes'),
    ('A017', 'Charles Petzold'),
    ('A018', 'David Thomas'),
    ('A019', 'Christian Keur'),
    ('A020', 'Douglas Crockford'),
    ('A021', 'Alan Beaulieu'),
    ('A022', 'Wes McKinney'),
    ('A023', 'Joshua Bloch'),
    ('A024', 'Andrew Ng'),
    ('A025', 'Randal L. Schwartz'),
    ('A026', 'David Beazley'),
    ('A027', 'Robert C. Martin'),
    ('A028', 'Luciano Ramalho'),
    ('A029', 'Jaime Buelta'),
    ('A030', 'Mark Lutz'),
    ('A031', 'Zed A. Shaw'),
    ('A032', 'Eric Freeman')
    ;
