INSERT INTO Book (ISBN, Title, AuthorID, SubjectArea, Description, BookType, IsLendable, Language, Binding, Edition)
VALUES 
    ('9780132350884', 'Database Systems: The Complete Book', 'A001', 'Computer Science', 'Comprehensive guide to databases.', 'Textbook', 'Y', 'English', 'Hardcover', '3rd Edition'),
    ('9780262531966', 'Introduction to Algorithms', 'A002', 'Computer Science', 'Fundamentals of algorithms and problem-solving techniques.', 'Textbook', 'Y', 'English', 'Paperback', '4th Edition'),
    ('9780596006624', 'Head First Design Patterns', 'A003', 'Computer Science', 'Design patterns explained in an engaging manner.', 'Educational', 'Y', 'English', 'Paperback', '1st Edition'),
    ('9780132350885', 'Clean Code: A Handbook', 'A004', 'Computer Science', 'Guides software developers in writing clean code.', 'Textbook', 'Y', 'English', 'Hardcover', '1st Edition'),
    ('9780060254926', 'Goodnight Moon', 'A005', 'Children''s Literature', 'Beloved bedtime story for children.', 'Fiction', 'Y', 'English', 'Board book', '25th Edition'),
    ('9781593275846', 'The Linux Command Line', 'A006', 'Computer Science', 'A comprehensive guide to the Linux command line.', 'Textbook', 'Y', 'English', 'Paperback', '1st Edition'),
    ('9781449331818', 'Data Science for Business', 'A007', 'Data Science', 'A practical introduction to data science concepts.', 'Educational', 'Y', 'English', 'Hardcover', '1st Edition'),
    ('9781449361327', 'Designing Data-Intensive Applications', 'A008', 'Computer Science', 'Principles behind scalable and reliable applications.', 'Textbook', 'Y', 'English', 'Hardcover', '1st Edition'),
    ('9781593275679', 'Automate the Boring Stuff with Python', 'A009', 'Computer Science', 'Teaches Python programming for automating tasks.', 'Educational', 'Y', 'English', 'Paperback', '2nd Edition'),
    ('9780262033848', 'Artificial Intelligence: A Modern Approach', 'A010', 'Computer Science', 'Comprehensive textbook on AI.', 'Textbook', 'Y', 'English', 'Hardcover', '3rd Edition'),
    ('9780134685991', 'Deep Learning', 'A011', 'Computer Science', 'Fundamentals of deep learning.', 'Textbook', 'Y', 'English', 'Hardcover', '1st Edition'),
    ('9781788995573', 'Hands-On Machine Learning with Scikit-Learn', 'A012', 'Computer Science', 'Practical guide to machine learning.', 'Educational', 'Y', 'English', 'Paperback', '2nd Edition'),
    ('9780262538408', 'Reinforcement Learning: An Introduction', 'A013', 'Computer Science', 'Classic introduction to reinforcement learning.', 'Textbook', 'Y', 'English', 'Hardcover', '2nd Edition'),
    ('9780201835953', 'The Mythical Man-Month: Software Engineering', 'A014', 'Computer Science', 'Essays on software project management.', 'Educational', 'Y', 'English', 'Paperback', '2nd Edition'),
    ('9780201616224', 'Design Patterns: Reusable Software', 'A015', 'Computer Science', 'A catalog of object-oriented design patterns.', 'Textbook', 'Y', 'English', 'Hardcover', '1st Edition'),
    ('9781118481348', 'Python Crash Course', 'A016', 'Computer Science', 'A fast-paced, thorough introduction to Python.', 'Educational', 'Y', 'English', 'Paperback', '2nd Edition'),
    ('9780465050659', 'Code: The Hidden Language - Hardware and Software', 'A017', 'Computer Science', 'A unique history of computer code.', 'Educational', 'Y', 'English', 'Paperback', '1st Edition'),
    ('9780061120084', 'The Pragmatic Programmer: Your Journey To Mastery', 'A018', 'Computer Science', 'Practical advice for programmers.', 'Educational', 'Y', 'English', 'Hardcover', '2nd Edition'),
    ('9780321856715', 'iOS Programming: The Big Nerd Ranch Guide', 'A019', 'Computer Science', 'Guide to iOS programming.', 'Educational', 'Y', 'English', 'Paperback', '7th Edition'),
    ('9781449318482', 'JavaScript: The Good Parts', 'A020', 'Computer Science', 'Focuses on the good parts of JavaScript.', 'Educational', 'Y', 'English', 'Paperback', '1st Edition'),
    ('9781449360733', 'Learning SQL', 'A021', 'Computer Science', 'A beginner-friendly guide to SQL.', 'Educational', 'Y', 'English', 'Paperback', '3rd Edition'),
    ('9781491936160', 'Python for Data Analysis', 'A022', 'Computer Science', 'Data analysis using Python.', 'Educational', 'Y', 'English', 'Paperback', '2nd Edition'),
    ('9780132122719', 'Effective Java', 'A023', 'Computer Science', 'Best practices in Java programming.', 'Educational', 'Y', 'English', 'Hardcover', '3rd Edition'),
    ('9781492049568', 'Machine Learning Yearning', 'A024', 'Computer Science', 'Practical advice for building learning systems.', 'Educational', 'Y', 'English', 'Paperback', '1st Edition'),
    ('9780596009205', 'Learning Perl', 'A025', 'Computer Science', 'Introduction to Perl programming.', 'Educational', 'Y', 'English', 'Paperback', '7th Edition'),
    ('9781491957664', 'Python Cookbook', 'A026', 'Computer Science', 'Recipes for mastering Python.', 'Educational', 'Y', 'English', 'Paperback', '3rd Edition'),
    ('9780596004484', 'Programming Perl', 'A027', 'Computer Science', 'Advanced Perl programming guide.', 'Educational', 'Y', 'English', 'Hardcover', '4th Edition'),
    ('9780133356722', 'Clean Architecture: Software Structure and Design', 'A028', 'Computer Science', 'Strategies for creating maintainable software.', 'Educational', 'Y', 'English', 'Hardcover', '1st Edition')
    ;